### ISSUE TITLE
No valid API Keypair Defined

### ISSUE THREAD

**Issue by jamesonessit** [tenable/integration-cscc#1]
ERROR:tenable.errors.UnexpectedValueError:No valid API Keypair Defined
Traceback (most recent call last):
  File "/usr/local/bin/tenable-cscc", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tenable_cscc/cli.py", line 67, in cli
    ua_identity='Tio2CSCC/{}'.format(__version__))
  File "/usr/local/lib/python3.5/dist-packages/tenable/io/__init__.py", line 247, in __init__
    raise UnexpectedValueError('No valid API Keypair Defined')
tenable.errors.UnexpectedValueError: No valid API Keypair Defined

**Comment by jamesonessit** [comment]
> ERROR:tenable.errors.UnexpectedValueError:No valid API Keypair Defined
> Traceback (most recent call last):
> File "/usr/local/bin/tenable-cscc", line 11, in 
> sys.exit(cli())
> File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in **call**
> return self.main(*args, **kwargs)
> File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
> rv = self.invoke(ctx)
> File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
> return ctx.invoke(self.callback, **ctx.params)
> File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
> return callback(*args, **kwargs)
> File "/usr/local/lib/python3.5/dist-packages/tenable_cscc/cli.py", line 67, in cli
> ua_identity='Tio2CSCC/{}'.format(**version**))
> File "/usr/local/lib/python3.5/dist-packages/tenable/io/**init**.py", line 247, in **init**
> raise UnexpectedValueError('No valid API Keypair Defined')
> tenable.errors.UnexpectedValueError: No valid API Keypair Defined

**Comment by SteveMcGrath** [comment]
Did you specify a set of api keys for the script to run with?

**Comment by Gribel** [comment]
I'm experiencing the same problem trying to use tenable-cscc on my GCP project.
I specified the API key generated from tenable.io on tenable-cscc.conf.
I  put the json generated from GCP into google-account.json.

**Comment by SteveMcGrath** [comment]
as the issue appears to be around the Tenable.io keypair, can you validate that the config file in /etc/tenable-cscc.conf has the TIO_ACCESS_KEY and TIO_SECRET_KEY values defined and uncommented?  This is typically the cause.  If you strip away all of the comments, you should have something similar to this:

```
TIO_ACCESS_KEY="0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
TIO_SECRET_KEY="0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
CSCC_ACCOUNT_FILE="/etc/google-account.json"
CSCC_SOURCE_ID="organizations/{ORGID}/sources/{SOURCEID}"
RUN_EVERY="24"
THREADS="2"
```

**Comment by Gribel** [comment]
Yes, it's exactly as expectate, without comments:

TIO_ACCESS_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
TIO_SECRET_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
CSCC_ACCOUNT_FILE="/etc/google-account.json"
CSCC_SOURCE_ID="organizations/xxxxxxxxxxxxxxx/sources/xxxxxxxxxxxxxxxxxxx"
RUN_EVERY="1"
THREADS="2"

At other side, when I check if the service is running with systemctl status tenable-cscc, there's another error:

tenable-cscc.service - Tenable.io to CSCC Bridge
   Loaded: loaded (/lib/systemd/system/tenable-cscc.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-07-30 19:37:19 UTC; 34min ago
 Main PID: 6308 (tenable-cscc)
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/tenable-cscc.service
           └─6308 /usr/bin/python3 /usr/local/bin/tenable-cscc

Jul 30 19:39:31 vm-tenable-io tenable-cscc[6308]:     "status": "INVALID_ARGUMENT"
Jul 30 19:39:31 vm-tenable-io tenable-cscc[6308]:   }
Jul 30 19:39:31 vm-tenable-io tenable-cscc[6308]: }
Jul 30 19:39:32 vm-tenable-io tenable-cscc[6308]: ERROR:tenable.errors.InvalidInputError:PATCH https://securitycenter.googleapis.com/v1beta1/organizations/{MY ORG ID}/sources/{MY SOURCE ID}/findings/1fe6405369769f75d1a3dcb401c
Jul 30 19:39:32 vm-tenable-io tenable-cscc[6308]:   "error": {
Jul 30 19:39:32 vm-tenable-io tenable-cscc[6308]:     "code": 400,
Jul 30 19:39:32 vm-tenable-io tenable-cscc[6308]:     "message": "Value is invalid. It must be NUMBER, STRING, OR BOOL.",
Jul 30 19:39:32 vm-tenable-io tenable-cscc[6308]:     "status": "INVALID_ARGUMENT"
Jul 30 19:39:32 vm-tenable-io tenable-cscc[6308]:   }
Jul 30 19:39:32 vm-tenable-io tenable-cscc[6308]: }

**Comment by Gribel** [comment]
Temporaly solved inputing the line in cscc.py:

**finding["sourceProperties"] = {}**

before the last 2 lines:

**return self._api.patch('{}/findings/{}'.format(
            self._api.source_id, finding_id), json=finding).json()**

Didn't solve the problem, but I can populate SCC with some info excluding Source Properties by now. Is there a solution for this case?

Looks like the propertie format on json is wrong.

**Comment by SteveMcGrath** [comment]
Interesting, I wonder if they changed the format post beta...  For the new issue, if you have a solution, can you please submit a PR with the change && and modify the test so it passes?

As for the the service, the service seems to be running alright if it's posting a finding.  Were you attempting to run the integration outside of the systemd service?  If you were, then you'd need to either add those variables into your environment or use the appropriate flags for it to run.

Further, if you set the log-level to debug, you can see the actual post that its trying to make.  If you could post that, it may be helpful in determining whats going on.

**Comment by SteveMcGrath** [comment]
Closed from lack of response.
